# Form implementation generated from reading ui file 'Voting_Application.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VotingMenu(object):
    def setupUi(self, VotingMenu):
        VotingMenu.setObjectName("VotingMenu")
        VotingMenu.resize(613, 622)
        self.centralwidget = QtWidgets.QWidget(parent=VotingMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.VotingApplication_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.VotingApplication_Label.setGeometry(QtCore.QRect(210, 60, 221, 51))
        self.VotingApplication_Label.setObjectName("VotingApplication_Label")
        self.ID_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.ID_Label.setGeometry(QtCore.QRect(150, 160, 41, 41))
        self.ID_Label.setObjectName("ID_Label")
        self.Matt_Button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Matt_Button.setGeometry(QtCore.QRect(270, 260, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Matt_Button.setFont(font)
        self.Matt_Button.setIconSize(QtCore.QSize(70, 70))
        self.Matt_Button.setObjectName("Matt_Button")
        self.Voting_Options = QtWidgets.QButtonGroup(VotingMenu)
        self.Voting_Options.setObjectName("Voting_Options")
        self.Voting_Options.addButton(self.Matt_Button)
        self.Jake_Button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Jake_Button.setGeometry(QtCore.QRect(270, 310, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Jake_Button.setFont(font)
        self.Jake_Button.setObjectName("Jake_Button")
        self.Voting_Options.addButton(self.Jake_Button)
        self.ID_Input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ID_Input.setGeometry(QtCore.QRect(210, 160, 191, 41))
        self.ID_Input.setObjectName("ID_Input")
        self.Candidates_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Candidates_Label.setGeometry(QtCore.QRect(240, 220, 141, 31))
        self.Candidates_Label.setObjectName("Candidates_Label")
        self.Vote_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Vote_Button.setGeometry(QtCore.QRect(230, 360, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Vote_Button.setFont(font)
        self.Vote_Button.setObjectName("Vote_Button")
        self.Vote_Cast_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Vote_Cast_Label.setGeometry(QtCore.QRect(260, 410, 111, 21))
        self.Vote_Cast_Label.setObjectName("Vote_Cast_Label")
        self.Already_Voted_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Already_Voted_Label.setGeometry(QtCore.QRect(250, 450, 131, 21))
        self.Already_Voted_Label.setObjectName("Already_Voted_Label")
        self.Error_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Error_Label.setGeometry(QtCore.QRect(40, 340, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Error_Label.setFont(font)
        self.Error_Label.setWordWrap(True)
        self.Error_Label.setObjectName("Error_Label")
        VotingMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=VotingMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 613, 26))
        self.menubar.setObjectName("menubar")
        VotingMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=VotingMenu)
        self.statusbar.setObjectName("statusbar")
        VotingMenu.setStatusBar(self.statusbar)

        self.retranslateUi(VotingMenu)
        QtCore.QMetaObject.connectSlotsByName(VotingMenu)

        self.Vote_Cast_Label.hide()
        self.Already_Voted_Label.hide()
        self.Error_Label.hide()

    def retranslateUi(self, VotingMenu):
        _translate = QtCore.QCoreApplication.translate
        VotingMenu.setWindowTitle(_translate("VotingMenu", "Voting Menu"))
        self.VotingApplication_Label.setText(_translate("VotingMenu", "<html><head/><body><p><span style=\" font-size:16pt;\">Voting Application</span></p></body></html>"))
        self.ID_Label.setText(_translate("VotingMenu", "<html><head/><body><p><span style=\" font-size:16pt;\">ID</span></p></body></html>"))
        self.Matt_Button.setText(_translate("VotingMenu", "Matt"))
        self.Jake_Button.setText(_translate("VotingMenu", "Jake"))
        self.Candidates_Label.setText(_translate("VotingMenu", "<html><head/><body><p><span style=\" font-size:16pt;\">Candidates</span></p></body></html>"))
        self.Vote_Button.setText(_translate("VotingMenu", "Submit Vote"))
        self.Vote_Cast_Label.setText(_translate("VotingMenu", "<html><head/><body><p><span style=\" font-size:12pt; color:#55aa00;\">Vote Casted</span></p></body></html>"))
        self.Already_Voted_Label.setText(_translate("VotingMenu", "<html><head/><body><p><span style=\" font-size:12pt; color:#ff0000;\">Already Voted</span></p></body></html>"))
        self.Error_Label.setText(_translate("VotingMenu", "<html><head/><body><p><span style=\" color:#ff0000;\">NEED TO ENTER A UNIQUE INT ID </span><span style=\" text-decoration: underline; color:#ff0000;\">AND</span><span style=\" color:#ff0000;\"> SELECT A CANDIDATE</span></p></body></html>"))
